# training
start_epoch: 1
max_epochs: 100
batch_size: 1
val_every: 1
learning_rate: 1e-3
learning_rate_train: 1e-4
learning_rate_pretrained: 1e-5
weight_decay: 1e-5
eta_min: 1e-5
eta_min_2: 5e-4

# path
log_path: /content/gdrive/MyDrive/KLTN/logs
source_folder_dataset_2D: /content/gdrive/MyDrive/KLTN/datasets/
source_folder_lits: /content/LITS17
source_folder_msd: /content/Task03_Liver
source_folder_custom_dataset: /content/custom_datasets
path_save_dataset_2D: /content/2D_dataset
path_save_model_state: /content/gdrive/MyDrive/KLTN/code/weight